const productsData = [
  { id: 1, name: "Apples", category: "Fruits", price: 120, unit: "per kg", discountPercent: 15, image: require("../assets/images/apple.png") },
  { id: 2, name: "Carrots", category: "Vegetables", price: 60, unit: "350 g", discountPercent: 10, image: require("../assets/images/carrot.png") },
  { id: 3, name: "Organic Milk", category: "Dairy", price: 50, unit: "1 ltr", discountPercent: 5, image: require("../assets/images/milk.png") },
  { id: 4, name: "Pineapple", category: "Fruits", price: 150, unit: "per pcs", discountPercent: 20, image: require("../assets/images/pineapple.png") },
  { id: 5, name: "Mango", category: "Fruits", price: 70, unit: "500 g", discountPercent: 10, image: require("../assets/images/mango.png") },
  { id: 6, name: "Banana", category: "Fruits", price: 40, unit: "8 pcs", discountPercent: 25, image: require("../assets/images/banana.png") },
  { id: 7, name: "Strawberry", category: "Fruits", price: 70, unit: "300 g", discountPercent: 15, image: require("../assets/images/strawberry.png") },
  { id: 8, name: "Dragon Fruit", category: "Fruits", price: 150, unit: "per pcs", discountPercent: 8, image: require("../assets/images/dragon.png") },
  { id: 9, name: "Orange", category: "Fruits", price: 65, unit: "500 g", discountPercent: 10, image: require("../assets/images/orange.png") },
  { id: 10, name: "Guava", category: "Fruits", price: 30, unit: "500 g", discountPercent: 12, image: require("../assets/images/guava.png") },
  { id: 11, name: "Papaya", category: "Fruits", price: 60, unit: "per pcs", discountPercent: 10, image: require("../assets/images/papaya.png") },
  { id: 12, name: "Black Grapes", category: "Fruits", price: 130, unit: "per kg", discountPercent: 20, image: require("../assets/images/Bgrape.png") },
  { id: 13, name: "Grapes", category: "Fruits", price: 70, unit: "per kg", discountPercent: 18, image: require("../assets/images/ggrape.png") },
  { id: 14, name: "Pomegranate", category: "Fruits", price: 180, unit: "per kg", discountPercent: 25, image: require("../assets/images/pomegranate.png") },
  { id: 15, name: "Watermelon", category: "Fruits", price: 49, unit: "per pcs", discountPercent: 8, image: require("../assets/images/watermelon.png") },
  { id: 16, name: "Potato", category: "Vegetables", price: 35, unit: "per kg", discountPercent: 12, image: require("../assets/images/potato.png") },
  { id: 18, name: "Tomato", category: "Vegetables", price: 25, unit: "450 g", discountPercent: 10, image: require("../assets/images/tomato.jpg") },
  { id: 19, name: "Lemon", category: "Vegetables", price: 20, unit: "200 g", discountPercent: 5, image: require("../assets/images/Lemon.png") },
  { id: 20, name: "Ginger", category: "Vegetables", price: 15, unit: "250 g", discountPercent: 8, image: require("../assets/images/ginger.png") },
  { id: 21, name: "Brinjal", category: "Vegetables", price: 55, unit: "500 g", discountPercent: 15, image: require("../assets/images/rbrinjal.png") },
  { id: 22, name: "Bell Pepper", category: "Vegetables", price: 85, unit: "4 pcs", discountPercent: 20, image: require("../assets/images/bellpepper.png") },
  { id: 23, name: "Onion", category: "Vegetables", price: 30, unit: "1 kg", discountPercent: 10, image: require("../assets/images/onion.jpg") },
  { id: 24, name: "Lettuce", category: "Vegetables", price: 69, unit: "500 g", discountPercent: 18, image: require("../assets/images/lettuce.png") },
  { id: 25, name: "Almond Milk", category: "Dairy", price: 250, unit: "1 ltr", discountPercent: 15, image: require("../assets/images/amilk.png") },
  { id: 27, name: "Buffalo Milk", category: "Dairy", price: 40, unit: "1 ltr", discountPercent: 5, image: require("../assets/images/bmilk.png") },
  { id: 28, name: "Oat Milk", category: "Dairy", price: 199, unit: "1 ltr", discountPercent: 10, image: require("../assets/images/omilk.png") },
  { id: 29, name: "Cow Milk", category: "Dairy", price: 49, unit: "1 ltr", discountPercent: 7, image: require("../assets/images/cmilk.png") },
  { id: 30, name: "Fresh Cheese", category: "Dairy", price: 170, unit: "500 g", discountPercent: 12, image: require("../assets/images/fcheese.png") },
  { id: 31, name: "Brie Cheese", category: "Dairy", price: 290, unit: "300 g", discountPercent: 18, image: require("../assets/images/briecheese.png") },
  { id: 32, name: "Cheddar Cheese", category: "Dairy", price: 180, unit: "450 g", discountPercent: 15, image: require("../assets/images/chedcheese.png") },
  { id: 33, name: "Cottage Cheese", category: "Dairy", price: 120, unit: "500 g", discountPercent: 10, image: require("../assets/images/ccheese.png") },
  { id: 34, name: "Sweet Cream Butter", category: "Dairy", price: 160, unit: "100 g", discountPercent: 15, image: require("../assets/images/sbutter.png") },
  { id: 35, name: "Oraganic Butter", category: "Dairy", price: 70, unit: "50 g", discountPercent: 10, image: require("../assets/images/obutter.jpg") },
  { id: 36, name: "Plain Yogurt", category: "Dairy", price: 90, unit: "500 g", discountPercent: 8, image: require("../assets/images/pyoghurt.png") },
  { id: 37, name: "Greek Yogurt", category: "Dairy", price: 325, unit: "500 g", discountPercent: 10, image: require("../assets/images/gyogurt.png") },
  { id: 38, name: "Wheat", category: "Grains", price: 2540, unit: "per kg", discountPercent: 30, image: require("../assets/images/wheat.png") },
  { id: 39, name: "Oats", category: "Grains", price: 240, unit: "per kg", discountPercent: 15, image: require("../assets/images/oats.png") },
  { id: 40, name: "Basmati Rice", category: "Grains", price: 800, unit: "per kg", discountPercent: 25, image: require("../assets/images/rice.png") },
  { id: 41, name: "Black Rice", category: "Grains", price: 900, unit: "per kg", discountPercent: 20, image: require("../assets/images/blrice.png") },
  { id: 42, name: "Brown Rice", category: "Grains", price: 500, unit: "per kg", discountPercent: 10, image: require("../assets/images/brice.png") },
  { id: 43, name: "Red Rice", category: "Grains", price: 300, unit: "per kg", discountPercent: 15, image: require("../assets/images/rrice.png") },
  { id: 44, name: "Maize", category: "Grains", price: 130, unit: "per kg", discountPercent: 10, image: require("../assets/images/corn.png") },
  { id: 45, name: "Barley", category: "Grains", price: 50, unit: "per kg", discountPercent: 5, image: require("../assets/images/barley.png") },
  { id: 46, name: "Rye", category: "Grains", price: 500, unit: "per kg", discountPercent: 20, image: require("../assets/images/rye.png") },
  { id: 47, name: "Sorghum", category: "Grains", price: 59, unit: "per kg", discountPercent: 12, image: require("../assets/images/sorghum.png") },
  { id: 48, name: "Millet", category: "Grains", price: 155, unit: "per kg", discountPercent: 10, image: require("../assets/images/millet.png") },
  { id: 49, name: "Quinoa", category: "Grains", price: 450, unit: "per kg", discountPercent: 25, image: require("../assets/images/quinoa.png") },
  { id: 50, name: "Bajra", category: "Grains", price: 19, unit: "per kg", discountPercent: 5, image: require("../assets/images/bajra.png") },
  { id: 51, name: "Ragi", category: "Grains", price: 45, unit: "per kg", discountPercent: 8, image: require("../assets/images/ragi.png") },
  { id: 52, name: "Jowar", category: "Grains", price: 90, unit: "per kg", discountPercent: 10, image: require("../assets/images/jawar.png") },
  { id: 53, name: "Soybean Oil", category: "Oils", price: 155, unit: "1 ltr", discountPercent: 10, image: require("../assets/images/soyaoil.png") },
  { id: 54, name: "Sunflower Oil", category: "Oils", price: 255, unit: "1 ltr", discountPercent: 8, image: require("../assets/images/sunoil.png") },
  { id: 55, name: "Canola Oil", category: "Oils", price: 300, unit: "1 ltr", discountPercent: 12, image: require("../assets/images/canoil.png") },
  { id: 56, name: "Olive Oil", category: "Oils", price: 1050, unit: "1 ltr", discountPercent: 20, image: require("../assets/images/olivoil.png") },
  { id: 57, name: "Groundnut Oil", category: "Oils", price: 350, unit: "1 ltr", discountPercent: 15, image: require("../assets/images/groundoil.png") },
  { id: 58, name: "Coconut Oil", category: "Oils", price: 400, unit: "1 ltr", discountPercent: 10, image: require("../assets/images/coconoil.png") },
  { id: 59, name: "Sesame Oil", category: "Oils", price: 210, unit: "1 ltr", discountPercent: 8, image: require("../assets/images/sesmoil.png") },
  { id: 60, name: "Flaxseed Oil", category: "Oils", price: 370, unit: "per kg", discountPercent: 12, image: require("../assets/images/flaxoil.png") },
  { id: 61, name: "Beef", category: "Meat", price: 240, unit: "per kg", discountPercent: 20, image: require("../assets/images/beef.png") },
  { id: 62, name: "Pork", category: "Meat", price: 370, unit: "per kg", discountPercent: 25, image: require("../assets/images/pork.jpg") },
  { id: 63, name: "Chicken Breast", category: "Meat", price: 279, unit: "per kg", discountPercent: 15, image: require("../assets/images/bchicken.png") },
  { id: 64, name: "Mutton", category: "Meat", price: 540, unit: "per kg", discountPercent: 20, image: require("../assets/images/mutton.png") },
  { id: 65, name: "Keema", category: "Meat", price: 550, unit: "per kg", discountPercent: 15, image: require("../assets/images/keema.jpg") },
  { id: 66, name: "Chicken Drumstick", category: "Meat", price: 245, unit: "per kg", discountPercent: 10, image: require("../assets/images/drchicken.png") },
  { id: 67, name: "Pork Ribs", category: "Meat", price: 350, unit: "per kg", discountPercent: 12, image: require("../assets/images/ripork.png") },
  { id: 68, name: "Bacon", category: "Meat", price: 260, unit: "per kg", discountPercent: 10, image: require("../assets/images/bacon.png") },
  { id: 69, name: "Chicken Sausage", category: "Meat", price: 180, unit: "per kg", discountPercent: 15, image: require("../assets/images/sausage.png") },
  { id: 70, name: "Lamb", category: "Meat", price: 600, unit: "per kg", discountPercent: 20, image: require("../assets/images/lamb.png") },
  { id: 71, name: "Pumpkin", category: "Vegetables", price: 78, unit: "per kg", discountPercent: 8, image: require("../assets/images/p.png") },
  { id: 72, name: "Brown Eggs", category: "Eggs", price: 40, unit: "6 pcs", discountPercent: 10, image: require("../assets/images/egg.jpg") },
  { id: 73, name: "Brown Eggs", category: "Eggs", price: 90, unit: "10 pcs", discountPercent: 12, image: require("../assets/images/egg1.jpg") },
  { id: 74, name: "White Eggs", category: "Eggs", price: 140, unit: "12 pcs", discountPercent: 10, image: require("../assets/images/egg2.jpg") },
  { id: 75, name: "Brown Eggs", category: "Eggs", price: 250, unit: "30 pcs", discountPercent: 18, image: require("../assets/images/egg3.png") },
].map((product) => {
  const discount = product.discountPercent ?? 0; // use your defined discount
  const discountedPrice = Math.round(product.price * (1 - discount / 100));
  return { ...product, discount, discountedPrice };
});

export default productsData;
