const suppliesData = [
  // 🌿 Fertilizers
  {
    id: 1,
    name: "Urea 46",
    category: "Fertilizers",
    price: 400,
    discount: 20,
    discountedPrice: 320,
    unit: "5 kg bag",
    image: require("../assets/images/f1.png"),
  },
  {
    id: 2,
    name: "Organic Micro Nutrient Fertilizer",
    category: "Fertilizers",
    price: 550,
    discount: 15,
    discountedPrice: 468,
    unit: "10 kg pack",
    image: require("../assets/images/f2.png"),
  },
  {
    id: 3,
    name: "NPK 20-20-20",
    category: "Fertilizers",
    price: 750,
    discount: 10,
    discountedPrice: 675,
    unit: "10 kg pack",
    image: require("../assets/images/f3.png"),
  },
  {
    id: 4,
    name: "Mix Micronutrient Chelated 12%",
    category: "Fertilizers",
    price: 300,
    discount: 25,
    discountedPrice: 225,
    unit: "5 kg bag",
    image: require("../assets/images/f4.png"),
  },
  {
    id: 5,
    name: "Organic Cow Dung Manure",
    category: "Fertilizers",
    price: 300,
    discount: 25,
    discountedPrice: 225,
    unit: "5 kg bag",
    image: require("../assets/images/f5.png"),
  },
  {
    id: 6,
    name: " Organic Compost",
    category: "Fertilizers",
    price: 550,
    discount: 25,
    discountedPrice: 360,
    unit: "5 kg bag",
    image: require("../assets/images/f6.png"),
  },
    {
    id: 7,
    name: "Vermicompost",
    category: "Fertilizers",
    price: 750,
    discount: 10,
    discountedPrice: 675,
    unit: "10 kg pack",
    image: require("../assets/images/f7.png"),
  },

  // 🌱 Seeds
  {
    id: 8,
    name: "Lentil (Toor)",
    category: "Seeds",
    price: 250,
    discount: 20,
    discountedPrice: 200,
    unit: "2 kg pack",
    image: require("../assets/images/lentil1.jpg"),
  },
  {
    id: 9,
    name: "Lentil (Chana)",
    category: "Seeds",
    price: 250,
    discount: 20,
    discountedPrice: 200,
    unit: "2 kg pack",
    image: require("../assets/images/lentil3.png"),
  },
  {
    id: 10,
    name: "Lentil (Masoor)",
    category: "Seeds",
    price: 250,
    discount: 20,
    discountedPrice: 200,
    unit: "2 kg pack",
    image: require("../assets/images/lentil4.png"),
  },
  {
    id: 11,
    name: "Lentil (Urad)",
    category: "Seeds",
    price: 250,
    discount: 20,
    discountedPrice: 200,
    unit: "2 kg pack",
    image: require("../assets/images/lentils5.png"),
  },
  {
    id: 12,
    name: "Millet Seeds",
    category: "Seeds",
    price: 300,
    discount: 10,
    discountedPrice: 270,
    unit: "2 kg pack",
    image: require("../assets/images/millsee.png"),
  },
  {
    id: 13,
    name: "Pea Seeds",
    category: "Seeds",
    price: 500,
    discount: 15,
    discountedPrice: 425,
    unit: "1 kg pack",
    image: require("../assets/images/peasee.png"),
  },
  {
    id: 14,
    name: "Potato Seeds",
    category: "Seeds",
    price: 200,
    discount: 10,
    discountedPrice: 180,
    unit: "250 g pack",
    image: require("../assets/images/posee.png"),
  },
    {
    id: 15,
    name:"Combine Harvester",
    category: "Equipment",
    price: 125649,
    discount: 10,
    discountedPrice: 123468,
    unit: "1 pcs",
    image: require("../assets/images/tr1.png"),
    },
    {
    id: 16,
    name:"265 Di Tractor",
    category: "Equipment",
    price: 135971,
    discount: 12,
    discountedPrice: 133780,
    unit: "1 pcs",
    image: require("../assets/images/tr2.png"),
    },
    {
    id: 17,
    name:"3043D Compact Tractor",
    category: "Equipment",
    price: 78908,
    discount: 5,
    discountedPrice: 77990,
    unit: "1 pcs",
    image: require("../assets/images/tr3.png"),
    },
    {
    id: 18,
    name:"Garden Trowel",
    category: "Tools",
    price: 450,
    discount: 18,
    discountedPrice: 240,
    unit: "1 pcs",
    image: require("../assets/images/tr.png"),
    },
        {
    id: 19,
    name:"Marbles Hunter's Axe",
    category: "Tools",
    price: 800,
    discount: 10,
    discountedPrice: 700,
    unit: "1 pcs",
    image: require("../assets/images/t9.png"),
    },
      {
    id: 20,
    name: "Wheet Seeds",
    category: "Seeds",
    price: 500,
    discount: 10,
    discountedPrice: 450,
    unit: "500 g pack",
    image: require("../assets/images/whse.png"),
  },
        {
    id: 21,
    name: "Pumpkin Seeds",
    category: "Seeds",
    price: 300,
    discount: 15,
    discountedPrice: 250,
    unit: "500 g pack",
    image: require("../assets/images/watse.png"),
  },
      {
    id: 22,
    name:"Massey Ferguson Tractor",
    category: "Equipment",
    price: 99708,
    discount: 5,
    discountedPrice: 97990,
    unit: "1 pcs",
    image: require("../assets/images/tr4.png"),
    },
    {
    id: 23,
    name: "Barley Seeds",
    category: "Seeds",
    price: 300,
    discount: 15,
    discountedPrice: 250,
    unit: "500 g pack",
    image: require("../assets/images/barsee.png"),
  },
          {
    id: 24,
    name: "Canola Seeds",
    category: "Seeds",
    price: 450,
    discount: 10,
    discountedPrice: 350,
    unit: "500 g pack",
    image: require("../assets/images/Canoseed.png"),
  },
{
    id: 25,
    name: "Groundnut Seeds",
    category: "Seeds",
    price: 600,
    discount: 15,
    discountedPrice: 550,
    unit: "500 g pack",
    image: require("../assets/images/gs.png"),
  },
  {
    id: 26,
    name: "Maize Seeds",
    category: "Seeds",
    price: 800,
    discount: 12,
    discountedPrice: 750,
    unit: "1 kg pack",
    image: require("../assets/images/maisee.png"),
  },
    {
    id: 27,
    name: "Onion Seeds",
    category: "Seeds",
    price: 150,
    discount: 5,
    discountedPrice: 100,
    unit: "250 g pack",
    image: require("../assets/images/os.png"),
  },
      {
    id: 28,
    name: "Glyphosate",
    category: "Pesticides",
    price: 1000,
    discount: 5,
    discountedPrice: 950,
    unit: "1 l pack",
    image: require("../assets/images/p1.png"),
  },
    {
    id: 29,
    name: "Atrazine",
    category: "Pesticides",
    price: 1050,
    discount: 15,
    discountedPrice: 850,
    unit: "1 l pack",
    image: require("../assets/images/p2.png"),
  },
       {
    id: 30,
    name: "Chlorocil",
    category: "Pesticides",
    price: 1590,
    discount: 25,
    discountedPrice: 1350,
    unit: "1 l pack",
    image: require("../assets/images/p3.png"),
  },
        {
    id: 31,
    name:"Fielding Mounted Disc Plough",
    category: "Equipment",
    price: 99708,
    discount: 15,
    discountedPrice: 87990,
    unit: "1 pcs",
    image: require("../assets/images/pl1.png"),
    },
    {
    id: 32,
    name:"Welded Bow Rake",
    category: "Tools",
    price: 1500,
    discount: 10,
    discountedPrice: 1450,
    unit: "1 pcs",
    image: require("../assets/images/ra.png"),
    },
       {
    id: 33,
    name:"Battery Sprayer Pump",
    category: "Tools",
    price: 35000,
    discount: 16,
    discountedPrice: 31050,
    unit: "1 pcs",
    image: require("../assets/images/s1.png"),
    },
       {
    id: 34,
    name:"Tractor Mounted Boom Sprayer",
    category: "Tools",
    price: 85900,
    discount: 14,
    discountedPrice: 81020,
    unit: "1 pcs",
    image: require("../assets/images/s2.png"),
    },
           {
    id: 35,
    name:"Garden Spade",
    category: "Tools",
    price: 6900,
    discount: 17,
    discountedPrice: 5549,
    unit: "1 pcs",
    image: require("../assets/images/sp.png"),
    },
           {
    id: 36,
    name:"Garden Sprinkler 180°",
    category: "Tools",
    price: 5900,
    discount: 14,
    discountedPrice: 4120,
    unit: "1 pcs",
    image: require("../assets/images/sp1.png"),
    },
            {
    id: 37,
    name:"Agricultural Cultivator",
    category: "Equipment",
    price: 99708,
    discount: 15,
    discountedPrice: 80970,
    unit: "1 pcs",
    image: require("../assets/images/t6.png"),
    },
];

export default suppliesData;
